name: checks

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ">=1.15"  # for shfmt
      - uses: pre-commit/action@v2.0.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dist: alpine
          - dist: debian10
            bsd: true
            network: none
    steps:
      - uses: actions/checkout@v2
      - run: >-
          docker run
          --name bash-completion
          --env CI=true
          --env DIST=${{matrix.dist}}
          --env BSD=${{matrix.bsd}}
          --env NETWORK=${{matrix.network}}
          ${NETWORK:+--network $NETWORK}
          --volume $PWD:/usr/src/bash-completion:ro
          --workdir /usr/src/bash-completion
          --tty
          vskytta/bash-completion:${{matrix.dist}}
          test/docker/docker-script.sh
        env:
          NETWORK: ${{matrix.network}}
