name: checks

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ">=1.15"  # for shfmt
      - uses: pre-commit/action@v2.0.0

  distcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dist: alpine
          #- dist: centos7
          - dist: debian10
          - dist: debian10
            bsd: true
          - dist: fedoradev
          #- dist: ubuntu14
    container:
      image: vskytta/bash-completion:${{matrix.dist}}
      env:
        CI: true
        DIST: ${{matrix.dist}}
        BSD: ${{matrix.bsd}}
      options: --tty
    steps:
      - uses: actions/checkout@v2
      - run: test/docker/docker-script.sh; ls -la

  # TODO releases config
  # - for tags [0-9]+.[0-9]+ in scop/bash-completion
  # - tarball should be in bash-completion-${GITHUB_REF##*/}.tar.xz
