name: checks

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ">=1.15"  # for shfmt
      - uses: pre-commit/action@v2.0.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          #- dist: alpine
          #  network: bridge
          - dist: debian10
            bsd: true
            network: none
    container:
      image: vskytta/bash-completion:${{matrix.dist}}
      env:
        CI: true
        DIST: ${{matrix.dist}}
        BSD: ${{matrix.bsd}}
        NETWORK: ${{matrix.network}}
      options: --tty --network ${{matrix.network}}
    steps:
      - uses: actions/checkout@v2
      - run: test/docker/docker-script.sh
